services:
  test-postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_budget_prisma
    ports:
      - 6508:5432
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes:
  postgres:
